# Generated by Django 3.1.2 on 2020-10-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('fback', models.TextField()),
                ('rating', models.IntegerField(default=5)),
            ],
        ),
    ]
